"use client";

import React, { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import {
  Unlock,
  Key,
  ArrowLeftRight,
  CheckCircle2,
  ArrowRight,
  LayoutGrid,
  SlidersHorizontal,
  Rocket,
  Check,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

export default function DomainTransferPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const steps = [
    {
      step: "01",
      icon: Unlock,
      title: "Unlock your domain",
      desc: "Unlock the domain with your current registrar to allow outbound transfer requests.",
    },
    {
      step: "02",
      icon: Key,
      title: "Get your transfer code",
      desc: "Request your authorization / EPP code from your current registrar's panel.",
    },
    {
      step: "03",
      icon: ArrowLeftRight,
      title: "Start your transfer",
      desc: "Enter your domain and authorization code securely inside the Nupat dashboard.",
    },
    {
      step: "04",
      icon: CheckCircle2,
      title: "You are done",
      desc: "Once the transfer completes, manage your domain, hosting, and emails in one interface.",
    },
  ];

  const features = [
    {
      icon: LayoutGrid,
      title: "One Dashboard",
      desc: "Manage your domains alongside your other Nupat cloud and application services.",
    },
    {
      icon: SlidersHorizontal,
      title: "Simple Management",
      desc: "Keep your DNS records, renewal schedules, and security locks securely in one reliable place.",
    },
    {
      icon: Rocket,
      title: "Built for Growth",
      desc: "Instantly connect your freshly transferred domain to advanced hosting, corporate email, and websites.",
    },
  ];

  const checklist = [
    "Your domain is unlocked with your current registrar",
    "You have your authorization / EPP code ready",
    "Your domain is eligible for transfer (typically registered >60 days ago)",
    "Your administrative contact information is correct and up to date",
  ];

  const faqs = [
    {
      q: "How long does a domain transfer take?",
      a: "Typically, domain transfers take between 5 to 7 days to complete. This timeframe depends on how quickly your current registrar releases the domain and verifies the security keys.",
    },
    {
      q: "What is an EPP / authorization code?",
      a: "An EPP code (also known as an authorization code, transfer key, or Auth-Info code) is a unique alphanumeric key generated by your current registrar to verify that you are the legitimate owner requesting the transfer.",
    },
    {
      q: "Will my website go offline during the transfer?",
      a: "No! As long as your existing nameservers remain unchanged during the transfer, your website and email accounts will continue functioning with zero downtime.",
    },
    {
      q: "Can I transfer any domain to Nupat?",
      a: "We support transfers for most global extensions (.com, .net, .org, .co, .io) as well as African country-code domains (.ng, .africa, etc.). Ensure your domain is at least 60 days old and unlocked.",
    },
    {
      q: "Can I transfer my domain away from Nupat later?",
      a: "Yes, absolutely. You are never locked in. You can unlock your domain and generate your EPP code directly from your Nupat Cloud dashboard anytime.",
    },
  ];

  return (
    <div className="flex flex-col bg-white">
      {/* ── 1. Hero Section ── */}
      <section className="relative pt-32 pb-14 sm:pt-36 sm:pb-16 lg:pt-38 lg:pb-18 overflow-hidden bg-white">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-8 items-center">
            {/* Left Column: Headline, subtext, CTA */}
            <div className="lg:col-span-6 xl:col-span-6 text-left z-10">
              <h1 className="text-3xl sm:text-4xl lg:text-[44px] xl:text-[48px] font-black text-[#031033] tracking-tight leading-[1.14]">
                Move your domain
                <span className="block mt-1">with Confidence</span>
              </h1>
              <p className="mt-5 text-[#5a6a85] text-sm sm:text-base lg:text-[17px] leading-relaxed max-w-lg font-normal">
                Transfer your existing domain and manage it alongside your other
                digital services. Simple, transparent, and built for builders.
              </p>
              <div className="mt-8">
                <Link
                  href="/dashboard/domain-transfer"
                  id="hero-transfer-btn"
                  className="btn-primary !rounded-[8px] py-3.5 px-7 sm:px-8 text-sm sm:text-base font-semibold text-white shadow-[0_2px_10px_rgba(23,135,212,0.35)] hover:shadow-[0_4px_16px_rgba(23,135,212,0.45)] transition-all cursor-pointer inline-flex items-center justify-center"
                >
                  Transfer Your Domain
                </Link>
              </div>
            </div>

            {/* Right Column: Hero Image (man in orange beanbag celebrating) */}
            <div className="lg:col-span-6 xl:col-span-6 flex justify-center lg:justify-end items-center relative">
              <div className="relative w-full max-w-[380px] sm:max-w-[440px] lg:max-w-[500px]">
                <Image
                  src="/domain-transfer.png"
                  alt="Move your domain with Confidence"
                  width={1024}
                  height={1024}
                  priority
                  className="w-full h-auto object-contain select-none pointer-events-none"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── 2. Transfer in a Few Steps Section ── */}
      <section className="bg-[#f8faff] py-14 sm:py-18 border-t border-b border-[#e8eff8]">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10 sm:mb-14">
            <h2 className="text-2xl sm:text-3xl lg:text-[38px] font-black text-[#031033] tracking-tight">
              Transfer your domain in a few steps
            </h2>
          </div>

          <div className="flex flex-col lg:flex-row items-stretch lg:items-center justify-between gap-4 sm:gap-5">
            {steps.map((item, idx) => {
              const Icon = item.icon;
              return (
                <React.Fragment key={item.step}>
                  <div className="bg-white rounded-2xl p-6 sm:p-7 border border-[#e2edfc] shadow-[0_2px_12px_rgba(0,0,0,0.02)] relative flex-1 min-h-[190px] flex flex-col justify-between hover:border-[#1787D4]/30 hover:shadow-[0_8px_25px_rgba(23,135,212,0.06)] transition-all">
                    {/* Watermark Number on Top-Right */}
                    <span className="absolute top-5 right-6 text-3xl sm:text-4xl font-black text-[#1787D4]/15 select-none pointer-events-none tracking-tight">
                      {item.step}
                    </span>

                    {/* Icon */}
                    <div className="w-10 h-10 rounded-xl bg-[#edf5ff] flex items-center justify-center mb-5 shrink-0">
                      <Icon className="w-5 h-5 text-[#1787D4]" />
                    </div>

                    {/* Text */}
                    <div>
                      <h3 className="text-base font-bold text-[#031033] mb-2">
                        {item.title}
                      </h3>
                      <p className="text-[#5a6a85] text-xs sm:text-sm leading-relaxed">
                        {item.desc}
                      </p>
                    </div>
                  </div>

                  {/* Arrow divider (desktop only) */}
                  {idx < steps.length - 1 && (
                    <div className="hidden lg:flex items-center justify-center text-[#1787D4] px-1 shrink-0">
                      <ArrowRight className="w-5 h-5 stroke-[2.2]" />
                    </div>
                  )}
                </React.Fragment>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── 3. Bring Everything Under One Roof Section ── */}
      <section className="bg-white py-14 sm:py-20 overflow-hidden">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-14 items-center">
            {/* Left Column: Heading and 3 Feature Cards */}
            <div className="lg:col-span-6 flex flex-col justify-center">
              <h2 className="text-3xl sm:text-4xl lg:text-[40px] font-black text-[#031033] tracking-tight mb-8 sm:mb-10 leading-tight">
                Bring everything
                <span className="block">under one roof</span>
              </h2>

              <div className="flex flex-col gap-4 sm:gap-5">
                {features.map((feat) => {
                  const Icon = feat.icon;
                  return (
                    <div
                      key={feat.title}
                      className="bg-white rounded-2xl p-5 sm:p-6 border border-[#e8eff8] shadow-[0_2px_12px_rgba(0,0,0,0.02)] flex items-start gap-4 hover:border-[#1787D4]/30 hover:shadow-md transition-all"
                    >
                      <div className="w-10 h-10 rounded-xl bg-[#edf5ff] flex items-center justify-center shrink-0 mt-0.5">
                        <Icon className="w-5 h-5 text-[#1787D4]" />
                      </div>
                      <div>
                        <h3 className="text-base font-bold text-[#031033] mb-1.5">
                          {feat.title}
                        </h3>
                        <p className="text-[#5a6a85] text-xs sm:text-sm leading-relaxed">
                          {feat.desc}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Right Column: Monitors passing paper image */}
            <div className="lg:col-span-6 flex justify-center items-center">
              <div className="relative w-full max-w-[480px]">
                <Image
                  src="/domain-transfer-1.png"
                  alt="Bring everything under one roof"
                  width={800}
                  height={500}
                  className="w-full h-auto object-contain select-none"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── 4. Before You Transfer Section ── */}
      <section className="bg-[#f8faff] relative py-14 sm:py-20 border-t border-b border-[#e8eff8] overflow-hidden">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-14 items-center">
            {/* Left Column: Heading and Checklist Box */}
            <div className="lg:col-span-6 flex flex-col justify-center">
              <h2 className="text-3xl sm:text-4xl lg:text-[40px] font-black text-[#031033] tracking-tight mb-8 sm:mb-10 leading-tight">
                Before you transfer
              </h2>

              <div className="bg-white rounded-2xl p-6 sm:p-8 border border-[#e2edfc] shadow-[0_2px_12px_rgba(0,0,0,0.02)] divide-y divide-[#edf2f7]">
                {checklist.map((item, idx) => (
                  <div
                    key={idx}
                    className={`flex items-center gap-3.5 ${
                      idx === 0
                        ? "pb-4"
                        : idx === checklist.length - 1
                          ? "pt-4"
                          : "py-4"
                    }`}
                  >
                    <div className="w-6 h-6 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0 border border-emerald-200">
                      <Check className="w-3.5 h-3.5 stroke-[2.8]" />
                    </div>
                    <span className="text-sm sm:text-base font-semibold text-[#031033] leading-snug">
                      {item}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Right Column: Hands with smartphone image */}
            <div className="lg:col-span-6 absolute right-0 bottom-0 flex justify-center items-center">
              <div className="relative w-full max-w-[420px]">
                <Image
                  src="/domain-transfer-2.png"
                  alt="Before you transfer checklist"
                  width={600}
                  height={600}
                  className="w-full h-auto object-contain select-none"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── 5. Frequently Asked Questions Section ── */}
      <section className="bg-white py-16 sm:py-24">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl sm:text-4xl lg:text-[38px] font-black text-[#031033] tracking-tight text-center mb-10 sm:mb-14">
            Frequently asked questions
          </h2>

          <div className="max-w-3xl mx-auto border border-[#e2edfc] rounded-xl bg-white divide-y divide-[#e2edfc] shadow-[0_2px_12px_rgba(0,0,0,0.02)] overflow-hidden">
            {faqs.map((faq, idx) => (
              <div key={idx} className="transition-colors">
                <button
                  type="button"
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                  className="w-full text-left py-5 px-6 sm:px-7 flex items-center justify-between gap-4 cursor-pointer group"
                >
                  <span className="font-bold text-sm sm:text-base text-[#031033] group-hover:text-[#1787D4] transition-colors">
                    {faq.q}
                  </span>
                  <span className="shrink-0 text-[#1787D4]">
                    {openFaq === idx ? (
                      <ChevronUp className="w-5 h-5 stroke-[2.5]" />
                    ) : (
                      <ChevronDown className="w-5 h-5 stroke-[2.5]" />
                    )}
                  </span>
                </button>
                {openFaq === idx && (
                  <div className="px-6 sm:px-7 pb-6 pt-0">
                    <p className="text-[#5a6a85] text-xs sm:text-sm leading-relaxed">
                      {faq.a}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
